add retry loop to Trivy

diff --git a/.github/workflows/build_push.yaml b/.github/workflows/build_push.yaml
--- a/.github/workflows/build_push.yaml
+++ b/.github/workflows/build_push.yaml
@@ -64,6 +64,8 @@ jobs:
       TRIVY_VERSION: "v0.56.2"
       TRIVY_DATABASES: '"ghcr.io/aquasecurity/trivy-db:2","public.ecr.aws/aquasecurity/trivy-db"'
       TRIVY_JAVA_DATABASES: '"ghcr.io/aquasecurity/trivy-java-db:1","public.ecr.aws/aquasecurity/trivy-java-db"'
+      TRIVY_MAX_RETRIES: 10
+      TRIVY_RETRY_DELAY: 20
       HADOLINT_VERSION: "2.12.0"
       ACTIONS_RUNNER_DEBUG: true
 
@@ -179,11 +181,35 @@ jobs:
       run: |
         printf ${{ secrets.CVE_ALLOWLIST }} > .trivyignore
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${{ env.TRIVY_VERSION }}
-        trivy image \
-          --db-repository ${{ env.TRIVY_DATABASES }} \
-          --java-db-repository ${{ env.TRIVY_JAVA_DATABASES }} \
-          ${{ steps.build-image.outputs.full_image_name }} \
-          --exit-code 1 --timeout=20m --scanners vuln --severity CRITICAL
+        for ((i=0; i<${{ env.TRIVY_MAX_RETRIES }}; i++)); do
+          echo "Attempt $((i + 1)) of ${{ env.TRIVY_MAX_RETRIES }}..."
+          
+          # Run Trivy and capture output
+          trivy image \
+            --db-repository ${{ env.TRIVY_DATABASES }} \
+            --java-db-repository ${{ env.TRIVY_JAVA_DATABASES }} \
+            ${{ steps.build-image.outputs.full_image_name }} \
+            --exit-code 1 --timeout=20m --scanners vuln --severity CRITICAL
+          EXIT_CODE=$?
+
+          # Check for TOOMANYREQUESTS error in the output
+          if [[ $EXIT_CODE -eq 0 ]]; then
+            echo "Trivy scan completed successfully."
+            break
+          elif echo "$OUTPUT" | grep -q "TOOMANYREQUESTS"; then
+            if [[ $i -lt ${{ env.TRIVY_MAX_RETRIES }} ]]; then
+              echo "Encountered TOOMANYREQUESTS error. Retrying in ${{ env.TRIVY_RETRY_DELAY }} seconds..."
+              sleep ${{ env.TRIVY_RETRY_DELAY }}
+            else
+              echo "TOOMANYREQUESTS error encountered after ${{ env.TRIVY_MAX_RETRIES }} attempts. Exiting."
+              exit 1
+            fi
+          else
+            echo "Trivy scan failed with a different error:"
+            echo "$OUTPUT"
+            exit $EXIT_CODE
+          fi
+        done
 
     # Push image to ACR
     # Pushes if this is a push to master or an update to a PR that has auto-deploy label
