feat: add more steps

diff --git a/.github/workflows/docker-build-test-upload.yaml b/.github/workflows/docker-build-test-upload.yaml
--- a/.github/workflows/docker-build-test-upload.yaml
+++ b/.github/workflows/docker-build-test-upload.yaml
@@ -71,3 +71,61 @@ jobs:
 
       - name: Echo disk usage after build completion
         run: ./.github/scripts/echo_usage.sh
+
+      - name: Add standard tag names (short sha, sha, and branch) and any other post-build activity
+        run: make post-build/${{ matrix.notebook }} REPO=${{ env.LOCAL_REPO }}
+
+      - name: Push image to local registry (default pushes all tags)
+        run: make push/${{ matrix.notebook }} REPO=${{ env.LOCAL_REPO }}
+
+      # Image testing
+      - name: Set Up Python for Test Suite
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10' 
+
+      - name: Set up venv for Test Suite
+        run: |
+          python -m pip install --upgrade pip
+          make install-python-dev-venv
+      
+      - name: Test image
+        run: make test/${{ matrix.notebook }} REPO=${{ env.LOCAL_REPO }}
+
+      # Free up space from build process (containerscan action will run out of space if we don't)
+      - run: ./.github/scripts/cleanup_runner.sh
+
+      # Scan image for vulnerabilities
+      - name: Aqua Security Trivy image scan
+      # see https://github.com/StatCan/aaw-private/issues/11 -- should be re-enabled
+        if: steps.notebook-name.outputs.NOTEBOOK_NAME != 'sas'
+        run: |
+          printf ${{ secrets.CVE_ALLOWLIST }} > .trivyignore
+          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${{ env.TRIVY_VERSION }}
+          
+          set +e
+
+          for ((i=0; i<${{ env.TRIVY_MAX_RETRIES }}; i++)); do
+            echo "Attempt $((i + 1)) of ${{ env.TRIVY_MAX_RETRIES }}..."
+
+            trivy image \
+              --db-repository ${{ env.TRIVY_DATABASES }} \
+              --java-db-repository ${{ env.TRIVY_JAVA_DATABASES }} \
+              ${{ steps.build-image.outputs.full_image_name }} \
+              --exit-code 10 --timeout=20m --scanners vuln --severity CRITICAL
+            EXIT_CODE=$?
+
+            if [[ $EXIT_CODE -eq 0 ]]; then
+              echo "Trivy scan completed successfully."
+              exit 0
+            elif [[ $EXIT_CODE -eq 10 ]]; then
+              echo "Trivy scan completed successfully. Some vulnerabilities were found."
+              exit 10
+            elif [[ $i -lt $(( ${{ env.TRIVY_MAX_RETRIES }} - 1))  ]]; then
+              echo "Encountered unexpected error. Retrying in ${{ env.TRIVY_RETRY_DELAY }} seconds..."
+              sleep ${{ env.TRIVY_RETRY_DELAY }}
+            else
+              echo "Unexpected error persists after ${{ env.TRIVY_MAX_RETRIES }} attempts. Exiting."
+              exit 1
+            fi
+          done
